---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="centos" tag="7"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="fedora" tag="rawhide"
    - image="ubuntu" tag="1804"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "0MW2akMgXqCqC42iPYcoUwQ2Q9NEjRTYtAzWm8lMmNTjn8ZcAoA7FkQlbTgxXwykjFBVbqWQCl5mpK3soYIYbMVm4V2VQwItSo6Af76w7FoclIWbE0p6OxzjOb8ACduuuBFnbRF0LMc4N0t+vOLvkhYUBFhsGortVvIBVH9vK4k/GnH+yzyr9bvSe/hswnMJzX7i6OrdBtUHba5D9PWq2l7DWBFK+TSeQCmnRf5YLzQ00tOvICtRKxkXWtfnCzwVbI1WwqRShn/ctlaVncCsmURa6AJTCCnRrW2XE5Q23C05o528Hx0tFUOrgtnDbIHB0QxCH8zuEnwh1pbMPYRs2ljwxwwKpEta6wjEMbp0sh0yHaqcnARegs2CPR17R5pHavrzdtaqmzcY+jWbOEMqNCZGWsezAg3tDKB85usH/RyObxb/uZ4SQ+WWWvbTUPqPw8D70yw/H8FREe6IBKsTBRDWMzqZMUvy/9lfd+hEyqfmdaK30ReGyj1fX4uX0XHGtgP0qxcxryP7acV5F9Qe27StFN015X6dkvhIoEGjNL+UFXFrnfA9qIe5Rz4i51LUtbzR9A2nhYa8xC4M2Fw/AgkFWZXxMTbmJsNWsvfGFXTUh5CxTLPJzYb7UPfNnSjh0K+bdZeZ6liJiiQ2pxmm24B0XGwtRaky3iHlnz0OCQQ="
  email: false
