---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.buildtools
  - name: robertdebock.epel
  - name: robertdebock.microsoft_repository_keys
  - name: robertdebock.python_pip
collections:
  - name: community.general
