---
# tasks file for azure_cli
- name: install azure-cli
  pip:
    name: azure-cli
    state: present
  register: azure_cli_install_azure_cli
  until: azure_cli_install_azure_cli is succeeded
  retries: 3
