---
# tasks file for azure_cli
- name: install azure-cli
  pip:
    name: azure-cli
    state: present
  register: azure_cli_install_using_pip
  until: azure_cli_install_using_pip is succeeded
  retries: 3
