---
# tasks file for azure_cli

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
    state: present
  when:
    - ansible_pkg_mgr in [ "apt" ]

- name: Add yum repository
  ansible.builtin.yum_repository:
    name: AzureCLI
    description: Azure CLI
    baseurl: "https://packages.microsoft.com/yumrepos/azure-cli"
    enabled: true
    gpgcheck: true
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
    priority: 1
  when:
    - ansible_pkg_mgr in [ "yum", "dnf", "dnf5" ]

- name: Add zypper repository
  community.general.zypper_repository:
    name: AzureCLI
    repo: 'https://packages.microsoft.com/yumrepos/azure-cli'
    state: present
  when:
    - ansible_pkg_mgr in [ "zypper" ]

- name: Install required packages for Azure CLI
  ansible.builtin.package:
    name: "{{ azure_cli_required_packages }}"
    state: present
  when:
    - ansible_cli_python_interpreter is not defined or ansible_cli_python_interpreter is not none

- name: Install pip package
  when:
    - ansible_pkg_mgr not in [ "apt", "yum", "dnf", "zypper", "dnf5" ]
  block:
    - name: Install pip package no flags
      ansible.builtin.pip:
        name: azure-cli
  rescue:
    - name: Retry install with --break-system-packages when supported
      ansible.builtin.pip:
        name: azure-cli
        break_system_packages: true
        extra_args: --break-system-packages

- name: Install
  ansible.builtin.package:
    name: azure-cli
    state: present
  when:
    - ansible_pkg_mgr in [ "apt", "yum", "dnf", "zypper", "dnf5" ]
