---
- name: Verify
  hosts: all

  tasks:
    - name: install bash
      ansible.builtin.package:
        name: bash
        state: present

    - name: try az
      ansible.builtin.command:
        cmd: az --version
